# Generated by Django 2.2.5 on 2021-07-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=False)),
                ('supplier', models.ManyToManyField(to='inventoryapi.Supplier')),
            ],
        ),
    ]
